spring.application.name=authService
spring.datasource.url=jdbc:mysql://localhost:3306/myauthdb
spring.datasource.username=root
spring.datasource.password=Abhu620
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect